# Aula 02 - Python

## Dados numéricos

In [6]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [7]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [8]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [9]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [10]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


# Dados de texto

In [11]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


# Dados tipo bool - lógica

In [12]:
a == 1

True

In [13]:
h = (a==1)
print(h)
type(h)

True


bool

In [14]:
h = (a==2)
print(h)
type(h)

False


bool

In [15]:
i = True
type(i)

bool

In [16]:
ii = 'True'
type(ii)

str

## Operação de comparação

In [17]:
# Operação ==
a==b

True

In [18]:

# Operação ><
a>b

False

In [19]:
# Operação !=
a!=b

False

In [20]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [21]:
# Soma 
a+b

2.0

In [22]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [23]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [24]:
# Divisão
a/b

1.0

In [25]:
# Potencia
5**2

25

In [26]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [27]:
math.exp(0)

1.0

In [28]:
math.exp(a)

2.718281828459045

In [29]:
math.exp(-10)

4.5399929762484854e-05

In [30]:
import math as mt
mt.log(c)

0.0

In [31]:

mt.log10(100)

2.0

## Listas

In [32]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [33]:

# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [34]:
myFirstList==a

False

In [36]:
myFirstList[0]==a

True

In [37]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [38]:
type(mySecList)

list

In [39]:
type(mySecList[2])

str

In [40]:
type(mySecList[1])

int

## Caminhos = path

In [41]:
path = r"C:\Users\mathe\Documents\GitHub\-ENS410064"
print(path)

C:\Users\mathe\Documents\GitHub\-ENS410064


In [45]:
path = "C:/Users/mathe/Documents/GitHub/-ENS410064"
print(path)

C:/Users/mathe/Documents/GitHub/-ENS410064


In [46]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore.txt', 'cd', 'pyEnv', 'README.md', 'scripts', 'venv']

In [47]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [48]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/mathe/Documents/GitHub/-ENS410064/.git'

In [49]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [50]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\mathe\\Documents\\GitHub\\-ENS410064\\venv\\Scripts'

In [51]:

# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\mathe\\Documents\\')

In [52]:
os.getcwd()

'C:\\Users\\mathe\\Documents'

In [53]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\mathe\Documents/test


In [54]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\mathe\Documents/test2


## Numpy arrays e Pandas DataFrames

In [55]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [56]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [57]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.49959723 0.49105691 0.64281952 0.56361059 0.09305077 0.18051912
  0.76888437 0.30918879 0.65813059 0.42859874]
 [0.10873557 0.71094073 0.42961771 0.24715902 0.67587972 0.17343985
  0.15517629 0.78020266 0.53808761 0.28877885]
 [0.5218439  0.38173239 0.33769203 0.72277691 0.64090933 0.41718228
  0.81463715 0.84957277 0.64469733 0.47933414]
 [0.79586655 0.36151075 0.12613152 0.72598504 0.88115906 0.98508741
  0.90000282 0.36487607 0.54577619 0.84920486]
 [0.56541651 0.0754912  0.61786058 0.37015832 0.48979757 0.71192376
  0.82183867 0.4501003  0.20228174 0.53082898]
 [0.53591612 0.44019576 0.41449733 0.78503753 0.23637258 0.84714441
  0.49099975 0.21028225 0.85855292 0.27704438]
 [0.10904728 0.15731048 0.72170801 0.71452674 0.55545314 0.84606261
  0.69918488 0.2010141  0.32781705 0.18301126]
 [0.91163948 0.94167691 0.8958849  0.89695068 0.45397158 0.97691596
  0.10227037 0.46723354 0.79806984 0.85447179]
 [0.2311417  0.18236545 0.74452808 0.23528957 0.23017116 0.79807187
  0.24852568

In [58]:
# Acessando valores da matriz
n[0,:]

array([0.49959723, 0.49105691, 0.64281952, 0.56361059, 0.09305077,
       0.18051912, 0.76888437, 0.30918879, 0.65813059, 0.42859874])

In [59]:

n[:,0]

array([0.49959723, 0.10873557, 0.5218439 , 0.79586655, 0.56541651,
       0.53591612, 0.10904728, 0.91163948, 0.2311417 , 0.83376116])

In [60]:
n[:,1:5]

array([[0.49105691, 0.64281952, 0.56361059, 0.09305077],
       [0.71094073, 0.42961771, 0.24715902, 0.67587972],
       [0.38173239, 0.33769203, 0.72277691, 0.64090933],
       [0.36151075, 0.12613152, 0.72598504, 0.88115906],
       [0.0754912 , 0.61786058, 0.37015832, 0.48979757],
       [0.44019576, 0.41449733, 0.78503753, 0.23637258],
       [0.15731048, 0.72170801, 0.71452674, 0.55545314],
       [0.94167691, 0.8958849 , 0.89695068, 0.45397158],
       [0.18236545, 0.74452808, 0.23528957, 0.23017116],
       [0.96305312, 0.03729329, 0.20253965, 0.01359931]])

In [61]:
n[0,1:5]

array([0.49105691, 0.64281952, 0.56361059, 0.09305077])

In [62]:
n[0,-1]

0.4285987418270425

In [63]:
n[0,4:-1]

array([0.09305077, 0.18051912, 0.76888437, 0.30918879, 0.65813059])

In [64]:
n[0,4:]

array([0.09305077, 0.18051912, 0.76888437, 0.30918879, 0.65813059,
       0.42859874])

In [65]:
an = np.log(n*5)
print(an)

[[ 0.91548487  0.89824266  1.16754664  1.0360462  -0.7651721  -0.10248065
   1.34662322  0.43563469  1.19108602  0.76220378]
 [-0.6093984   1.2682717   0.76457839  0.21171459  1.21769777 -0.14248649
  -0.25375554  1.36123634  0.98970403  0.3673438 ]
 [ 0.95905114  0.64640245  0.52381695  1.28478324  1.16457063  0.73520588
   1.40442544  1.44641624  1.17046359  0.87408057]
 [ 1.38111416  0.59197441 -0.46099219  1.28921204  1.48292078  1.59441301
   1.50408054  0.6012404   1.00389161  1.44598308]
 [ 1.03924528 -0.97430128  1.12794547  0.61561343  0.89567482  1.26965347
   1.41322674  0.81115307  0.01134409  0.97612252]
 [ 0.98566028  0.78890218  0.72874917  1.36741416  0.16709194  1.44355381
   0.89812626  0.05013333  1.45693095  0.32586033]
 [-0.60653579 -0.24009593  1.28330327  1.27330306  1.02146689  1.442276
   1.25159784  0.00505767  0.49413831 -0.0887697 ]
 [ 1.51692724  1.54934486  1.49949458  1.50068351  0.81971723  1.58608327
  -0.6706974   0.84851185  1.38387875  1.45216612]
 [